version: "3.8"

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwerty
    networks:
      - app-network

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: qwerty
      ME_CONFIG_MONGODB_URL: mongodb://admin:qwerty@mongodb:27017
    depends_on:
      - mongodb
    networks:
      - app-network

  node-app:
    build: .  # Builds from the Dockerfile in the same directory
    ports:
      - "3000:3000"  # Map to your app's port
    depends_on:
      - mongodb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge